### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by legendsneverdie95** [lovac42/SpellingPolice#1]
I downloaded it and the spelling police check is on but it's not telling me if I misspelled a word. Can you please tell me what's wrong?

**Comment by lovac42** [comment]
Sounds like the dictionary wasn't installed correctly. Could you try the english one first.
```
Once you have it setup, edit spellpopo.py and add your dictionary file to the list.
```
Requires at least anki 2.1.10+

**Comment by dspjm** [comment]
I can't get this to work. Locations is right. 2.1.19
