### ISSUE TITLE
ERRor 

### ISSUE THREAD

**Issue by aboali19** [lovac42/SpellingPolice#11]
Don't appear.
Windows 10 
Anki 2.1.48
![Screenshot (3)](https://user-images.githubusercontent.com/91283119/136077221-8320d8ed-0978-4cd1-8a01-9bfdcf5969eb.png)

**Comment by lovac42** [comment]
I guess some of the hooks changed. I'm afraid I don't use or plan to support newer versions. And there will be more changes coming.
