### ISSUE TITLE
Replacement Suggestions Not Showing up

### ISSUE THREAD

**Issue by drmarmalademd** [lovac42/SpellingPolice#6]
I am on Anki 2.1.22 on a mac.

I have the en_us_9.0 dictionary installed. The add-on correctly identifies misspelled words; however, it does not offer replacement suggestions for the words. Any ideas?

![Screen Shot 2020-03-24 at 2 24 30 PM](https://user-images.githubusercontent.com/54896103/77463407-f7bf5b80-6ddb-11ea-9052-56b5b0669b24.png)

**Comment by lovac42** [comment]
Check config settings.

**Comment by drmarmalademd** [comment]
These are my config settings:
{
    "auto_startup": true,
    "bold_text": true,
    "check_during_review": true,
    "duck_mode": false
}

I have also tried using the default settings; still no change.

I am not sure which one will enable the suggestions to show up?

**Comment by dgeranton** [comment]
Hello,

Activate *duck_mode : true*

Le 24/03/2020 à 20:55, drmarmalademd a écrit :

**Comment by drmarmalademd** [comment]
*Facepalm*

Obviously! Thank you for your help.
